### ISSUE TITLE
elektroid hangs with 100% cpu while transferring samples

### ISSUE THREAD

**Issue by snd1** [dagargo/elektroid#26]
elektroid hangs with 100% cpu

- when transferring samples more than ~30-50 samples and double clicking on a directory of the device in the gui
<del>- randomly when transferring more than ~30-50 samples at once</del>

the gui can not be closed, `killall elektroid` does not work at all, somehow only a `kill -9 <pid>` works.

**Comment by snd1** [comment]
Happened not so far with small samples ~50kb

**Comment by dagargo** [comment]
I haven't been able to replicate the issue. I've successfully uploaded many long samples (larger that 1 MB) while browsing the device and creating and deleting directories.

Are you using the master? In commit 23c50f42b8a5e1a87f649d6c08c53a2c489e073f I fixed a bug that was causing signals not to be treated properly and causing a loop that could explain this behaviour. However, I've tried to replicate the bug in the previous commit and I couldn't either.

**Comment by snd1** [comment]
sorry for the late reply.

with the current master the 1st problem still appears but with more than 30-50 samples (around 0,5mb) in different subfolders and by clicking or doubleclicking through the subdirectories of the device forth and back.

the randomly crash so far didn't happen anymore

**Comment by dagargo** [comment]
I have been debugging and fixing some issues for the last weeks. It's not perfect yet but works nicer in many cases.

There were a couple of bugs that could have caused the freezes. One was causing the timeout not to be detected (527d658071d25b17c586397a58a4847f8f3a019e); the other was causing to not have available data on readings (a58d5b54c08bb5a045023d15e4981cab11f9f0d7), finally ending up in freezes or disconnections.

Also, I changed the way readings where made (053557e443cd30c760a08eb503a01d3316dbb77f). Now, a buffer is used instead of reading bytes one by one. This is a much better approach and has fixed occasional misreadings.

I still haven't fallen into the 100% CPU bug but I'm on it night now.

**Comment by dagargo** [comment]
I discovered another bug that could cause this behavior.

Sometimes, the device was sending empty SysEx messages to the computer (`f0 f7`) and, of course, these needed to be ignored. At the same time, there was a bug in which when a message was detected, the rest of the input buffer was discarded. Whenever this two conditions met, it would have caused a 100% CPU freeze. It's been fixed in 73b618650b318dd6127e9f27e472e6ab7575dd5e.

Besides that, Elektroid uses now polling when reading (63bbbb3129bc96adfa5697c28828e93af9cc88d0), which is a much better approach.

Also, there were some problems with input buffer overruns on old hardware so I increased the size of the input ring buffer (97084ccdeee1b60d74737ab255528ef8ef11db88). Perhaps, this could lead to freezes but I only found timeouts during my tests.

Lately, I've been testing Elektroid a lot because I realized that it was not working properly on quite old hardware but what it really meant is that under certain conditions some bugs were emerging. I'm quite sure I've fixed the bugs I detected but it would be super nice if you could check if these improvements fix your issues.

TIA.

**Comment by snd1** [comment]
Thanks a lot, elektroid does not hang anymore, as far as i tested it.

But huge sample transfers have problems, see #29

**Comment by dagargo** [comment]
Thank you so much for taking the time to test it.
