### ISSUE TITLE
Add support for TM-1

### ISSUE THREAD

**Issue by dagargo** [dagargo/elektroid#64]
The goal is to transmit samples to Machinedrum via TM-1.

TM-1 is a standard USB to MIDI (DIN5) interface that can also speed up MIDI transmission if the Elektron devices connected to them allow that.

As it seems that the underlying protocol is standard MIDI SDS, perhaps we could extend this functionality to any other device that supports it too.

Here we have some useful links taken from [here](https://www.elektronauts.com/t/do-i-need-to-convert-samples-before-loading-into-the-mduw/19001/2).

Format:
[http://elektron-users.com/index.php?option=com_openwiki&Itemid=43&id=waveforms_samples 94](http://elektron-users.com/index.php?option=com_openwiki&Itemid=43&id=waveforms_samples)

Batch conversion:
[http://www.elektronauts.com/t/best-software-for-batch-sample-rate-conversion/510](https://www.elektronauts.com/t/best-software-for-batch-sample-rate-conversion/510)

Discussion:
[http://www.elektron-users.com/index.php?option=com_fireboard&Itemid=28&func=view&id=30234&catid=9&limit=10&limitstart=0 27](http://www.elektron-users.com/index.php?option=com_fireboard&Itemid=28&func=view&id=30234&catid=9&limit=10&limitstart=0)

**Comment by dagargo** [comment]
More official information at [Elektronauts](https://www.elektronauts.com/files/473) but not related to samples.

**Comment by dagargo** [comment]
Working MIDI SDS pushed to branch [sds](https://github.com/dagargo/elektroid/tree/sds).

As I don't have a TM-1, I suggest you to work over the `connector_handshake_midi_sds` function in https://github.com/dagargo/elektroid/blob/bdddae89b1671df2b49c1778ae33590ed9051468/src/connector.c#L2506.

**Comment by dagargo** [comment]
Basic SDS support completed.

**Comment by dagargo** [comment]
`sds` branch merged into master and deleted.

**Comment by dagargo** [comment]
A lot of refactoring has been going on lately so the instructions above are obsolete.

In order to send a custom SysEx message to the TM-1, the code should be added at the end of this function. Other devices will ignore it so it will be safe.

https://github.com/dagargo/elektroid/blob/aff3aab084b89a5dc9492560b7e4d5aee4f8ce45/src/connectors/sds.c#L763-L785

Notice that we are assuming that TM-1 has only one MIDI interface and it's reading **and** bypassing the messages.

**Comment by robysweettrip** [comment]
I am going to **try** to test this out tomorrow (PST). I emphasize "try" because my TM-1 is really unstable in my Linux/Lenovo laptop because I have to do this plug/unplug/plug-while-holding-the-the-turbo-button dance to get it to stay recognized by the machine/OS, and even then, I haven't been able to get a simple command like `amidi -p hw:1,0 -s some_file.syx -i 20` to work with it, while it works fine with an equally as old Native Instruments Audio Kontrol 1 audio/MIDI interface.

PS, this is in response to your recent post on Elektronauts. I didn't want to reply there as I think a technical conversation may be more relevant here.

**Comment by dagargo** [comment]
> PS, this is in response to your recent post on Elektronauts. I didn't want to reply there as I think a technical conversation may be more relevant here.

Abosulutely! Fully agree.

I forgot to mention that, for now, you should change the following line.

```
#define SDS_BITS 16
```

I think it'a a 12 there in your case. We should set a variable depending on the MIDI identity reply but we'll do it later.

**Comment by dagargo** [comment]
Any news on this?

I've just pushed a few commits that should improve the SDS functionality. It's been tested and works well with my Digitakt (only upload)) and my E-Mu ESI-2000 (except when the device doesn't send the last byte).

Now, there are 4 filesystems; for 8, 12, 14 and 16 bits transmissions.

I'm still trying to figure out a couple of issues but hopefully this won't affect you if the Machinedrum MIDI SDS code is the same it's in the Digitakt.

One of the issues is the Receive SysEx option in the menu, it's not working ATM.

**Comment by robysweettrip** [comment]
Hey, sorry about the delay due to unforeseen personal things.

I meant to test this exclusively with my TM-1, but with my current Linux setup, the TM-1 just doesn't want to connect permanently. I will keep trying since I have in fact been able to connect it to the laptop well by doing a bunch of brute force connecting and disconnecting maneuvers. That said, in the times that I have managed to keep it connected, Turbo mode hasn't worked.

With that in mind, do you need me, or is it possible and beneficial, to test the new changes to Elektriod on the Machinedrum **without having to use the TM-1**, i.e., can I use it with, say, my Native Instruments Komplete Audio 6 MKII?

**Comment by dagargo** [comment]
> Hey, sorry about the delay due to unforeseen personal things.

No worries. First things first.

> With that in mind, do you need me, or is it possible and beneficial, to test the new changes to Elektriod on the Machinedrum without having to use the TM-1, i.e., can I use it with, say, my Native Instruments Komplete Audio 6 MKII?

Testing the TM-1 should be the last thing to do. Right now, I need you because I'd like you to test the SDS against the Machinedrum and the integration in Elektroid and using Komplete Audio 6 MKII is perfectly fine. Later, we'll see how to integrate the TM-1 and its turbo mode.

As a side note, Elektroid offers direct sample copying with the GUI (and CLI) but also SysEx sending via the app menu (soon via the CLI too). The latter can be used to send the SysEx files found in [these sample packs](https://www.elektron.se/en/all-products/sound-packs?filter=2689). BTW, SysEx sending only allows to send a single file but I'm working on sending multiple files at once.

Regarding a better integration with the Machinedrum, could you post here the output of `elektroid -vv` when selecting it in the device combo? I'd like to add a few tweaks if possible.

TIA.

**Comment by dagargo** [comment]
FYI, the bugs I mentioned a few days ago are fixed. Also, multiple SysEx uploading is now possible as well as using the CLI to send and receive SysEx.

**Comment by dagargo** [comment]
A couple of bugs have been fixed.

Also, an occasional error with an E-Mu ESI-2000 when downloading has been addressed with a little hack. Apparently, the sampler was not transmitting the last packet if it had only a single sample which cancelled the whole download. Now, Elektroid uploads an additional `0` sample if this is the case and then downloading just works. This affects all MIDI SDS devices but a single sample in this scenario is not much.

**Comment by dagargo** [comment]
Any update on this?

**Comment by dagargo** [comment]
Version 2. 2 is almost ready. I'm planning to release it during the following couple of weeks.

For anyone reading this, have you been able to use the SDS connector in Elektroid with the Machinedrum or other SDS supporting sampler?

**Comment by dagargo** [comment]
Has anyone been able to test SDS or the TM-1 with Elektroid?

**Comment by dagargo** [comment]
In case anyone is interested, a few improvements have been added to the SDS code.

WAIT packages are sent now to better control the device and avoid the 20 ms timeout specified in the protocol that caused devices to continue without further handshakings.

Besides, a couple of retry loops have been added to better recover in case of failure.

**Comment by erroreyes** [comment]
I finally got a stable Linux + TM-1 setup. Previously, I couldn't get the TM-1 to stay connect for longer than 30 seconds no matter what I would do. I can properly look into this now that everything seems almost fine. Anyway, to start, a question:

I don't seem to see any support for SDS transfers using the UI version. Does Elektroid only support SDS transfers via cli?

**Comment by erroreyes** [comment]
> What device are you trying to connect to? A Machinedrum?

Yes, I am doing the test with a Machinedrum and a TM-1. I have a Monomachine as well, but I'll stick to the MD to make testing simple for now.

Assuming that I should disconnect all MIDI instruments but leave the TM-1 connected via USB, this is what `elektroid -vvv` displayed when I selected the TM-1 from the dropdown menu:

```
DEBUG:preferences.c:132:(preferences_load): Loading preferences from '/home/roby/.config/elektroid/preferences.json'...
DEBUG:audio.c:231:(audio_init): Initializing audio (PulseAudio 16.1.0)...
DEBUG:editor.c:645:(editor_stop_load_thread): Stopping load thread...
DEBUG:audio_pa.c:325:(audio_server_info_callback): Using 48000 Hz sample rate...
DEBUG:audio.c:274:(audio_reset_sample): Resetting sample...
DEBUG:backend_alsa.c:363:(backend_get_system_subdevices): Adding hw:1 (name 'Elektron TM-1', subname 'Elektron TM-1 MIDI 1')...
DEBUG:elektroid.c:247:(elektroid_load_devices): Loading devices...
DEBUG:elektroid.c:267:(elektroid_load_devices): Selecting device -1...
DEBUG:audio_pa.c:290:(audio_connect_playback_stream_callback): Sink index: 1623
DEBUG:audio.c:61:(audio_write_to_output): Writing 256 frames...
DEBUG:audio_pa.c:305:(audio_connect_record_stream_callback): Sink index: 1624
DEBUG:audio_pa.c:252:(audio_set_sink_volume): Setting volume to 1.000000...
DEBUG:audio_pa.c:252:(audio_set_sink_volume): Setting volume to 1.000000...
DEBUG:sample.c:492:(sample_set_sample_info): Loop start at 3044, loop end at 3044
DEBUG:sample.c:492:(sample_set_sample_info): Loop start at 6074, loop end at 6074
DEBUG:backend_alsa.c:363:(backend_get_system_subdevices): Adding hw:1 (name 'Elektron TM-1', subname 'Elektron TM-1 MIDI 1')...
DEBUG:sample.c:492:(sample_set_sample_info): Loop start at 14361, loop end at 14361
DEBUG:elektroid.c:247:(elektroid_load_devices): Loading devices...
DEBUG:sample.c:492:(sample_set_sample_info): Loop start at 28722, loop end at 28722
DEBUG:sample.c:492:(sample_set_sample_info): Loop start at 54524, loop end at 54524
DEBUG:sample.c:492:(sample_set_sample_info): Loop start at 6280, loop end at 6280
DEBUG:sample.c:492:(sample_set_sample_info): Loop start at 6847, loop end at 6847
DEBUG:sample.c:492:(sample_set_sample_info): Loop start at 28596, loop end at 28596
DEBUG:sample.c:492:(sample_set_sample_info): Loop start at 28631, loop end at 28631
DEBUG:elektroid.c:267:(elektroid_load_devices): Selecting device -1...
DEBUG:sample.c:492:(sample_set_sample_info): Loop start at 4424, loop end at 4424
DEBUG:editor.c:680:(editor_set_volume_callback_bg): Setting volume to 1.000000...
DEBUG:sample.c:492:(sample_set_sample_info): Loop start at 5675, loop end at 5675
DEBUG:sample.c:492:(sample_set_sample_info): Loop start at 6331, loop end at 6331
DEBUG:sample.c:492:(sample_set_sample_info): Loop start at 3828, loop end at 3828
DEBUG:sample.c:492:(sample_set_sample_info): Loop start at 28869, loop end at 28869
DEBUG:sample.c:492:(sample_set_sample_info): Loop start at 5251, loop end at 5251
DEBUG:sample.c:492:(sample_set_sample_info): Loop start at 28762, loop end at 28762
DEBUG:sample.c:492:(sample_set_sample_info): Loop start at 6591, loop end at 6591
DEBUG:sample.c:492:(sample_set_sample_info): Loop start at 6271, loop end at 6271
DEBUG:sample.c:492:(sample_set_sample_info): Loop start at 7164, loop end at 7164
DEBUG:sample.c:492:(sample_set_sample_info): Loop start at 28707, loop end at 28707
DEBUG:sample.c:492:(sample_set_sample_info): Loop start at 54858, loop end at 54858
DEBUG:sample.c:492:(sample_set_sample_info): Loop start at 27777, loop end at 27777
DEBUG:sample.c:492:(sample_set_sample_info): Loop start at 4341, loop end at 4341
DEBUG:sample.c:492:(sample_set_sample_info): Loop start at 3674, loop end at 3674
DEBUG:sample.c:492:(sample_set_sample_info): Loop start at 48067, loop end at 48067
DEBUG:sample.c:492:(sample_set_sample_info): Loop start at 2950, loop end at 2950
DEBUG:sample.c:492:(sample_set_sample_info): Loop start at 7059, loop end at 7059
DEBUG:sample.c:492:(sample_set_sample_info): Loop start at 14450, loop end at 14450
DEBUG:sample.c:492:(sample_set_sample_info): Loop start at 6858, loop end at 6858
DEBUG:editor.c:680:(editor_set_volume_callback_bg): Setting volume to 1.000000...
DEBUG:editor.c:329:(editor_draw_waveform): Drawing waveform from 0 with 0x zoom...
DEBUG:notifier.c:32:(notifier_set_dir): Changing local browser path to '/home/roby/Music/Samples/drums/Roland Tr-707'...
DEBUG:notifier.c:140:(notifier_set_active): Starting local notifier...
DEBUG:notifier.c:66:(notifier_run): local notifier running...
DEBUG:editor.c:329:(editor_draw_waveform): Drawing waveform from 0 with 0x zoom...
DEBUG:editor.c:329:(editor_draw_waveform): Drawing waveform from 0 with 0x zoom...
DEBUG:editor.c:329:(editor_draw_waveform): Drawing waveform from 0 with 0x zoom...
DEBUG:editor.c:329:(editor_draw_waveform): Drawing waveform from 0 with 0x zoom...
DEBUG:editor.c:329:(editor_draw_waveform): Drawing waveform from 0 with 0x zoom...
DEBUG:editor.c:329:(editor_draw_waveform): Drawing waveform from 0 with 0x zoom...
DEBUG:editor.c:329:(editor_draw_waveform): Drawing waveform from 0 with 0x zoom...
DEBUG:editor.c:329:(editor_draw_waveform): Drawing waveform from 0 with 0x zoom...
DEBUG:editor.c:329:(editor_draw_waveform): Drawing waveform from 0 with 0x zoom...
DEBUG:editor.c:329:(editor_draw_waveform): Drawing waveform from 0 with 0x zoom...
DEBUG:editor.c:329:(editor_draw_waveform): Drawing waveform from 0 with 0x zoom...
DEBUG:editor.c:329:(editor_draw_waveform): Drawing waveform from 0 with 0x zoom...
DEBUG:editor.c:329:(editor_draw_waveform): Drawing waveform from 0 with 0x zoom...
DEBUG:editor.c:329:(editor_draw_waveform): Drawing waveform from 0 with 0x zoom...
DEBUG:editor.c:329:(editor_draw_waveform): Drawing waveform from 0 with 0x zoom...
DEBUG:editor.c:329:(editor_draw_waveform): Drawing waveform from 0 with 0x zoom...
DEBUG:editor.c:329:(editor_draw_waveform): Drawing waveform from 0 with 0x zoom...
DEBUG:editor.c:329:(editor_draw_waveform): Drawing waveform from 0 with 0x zoom...
DEBUG:editor.c:329:(editor_draw_waveform): Drawing waveform from 0 with 0x zoom...
DEBUG:editor.c:329:(editor_draw_waveform): Drawing waveform from 0 with 0x zoom...
DEBUG:elektroid.c:2352:(elektroid_fill_fs_combo_bg): Selecting first filesystem...
DEBUG:browser.c:620:(browser_load_dir): Browser already loading. Skipping load...
DEBUG:notifier.c:32:(notifier_set_dir): Changing remote browser path to '/'...
DEBUG:notifier.c:140:(notifier_set_active): Starting remote notifier...
DEBUG:notifier.c:66:(notifier_run): remote notifier running...
DEBUG:editor.c:329:(editor_draw_waveform): Drawing waveform from 0 with 0x zoom...
DEBUG:editor.c:329:(editor_draw_waveform): Drawing waveform from 0 with 0x zoom...
DEBUG:editor.c:329:(editor_draw_waveform): Drawing waveform from 0 with 0x zoom...
DEBUG:backend.c:389:(backend_destroy): Destroying backend...
DEBUG:progress.c:140:(elektroid_new_progress_thread_gsourcefunc): Creating SysEx thread...
DEBUG:backend.c:367:(backend_init): Initializing backend (ALSA) to 'hw:1,0,0'...
DEBUG:backend_alsa.c:85:(backend_init_int): Setting blocking mode...
DEBUG:backend.c:685:(backend_rx_drain): Draining buffers...
DEBUG:editor.c:329:(editor_draw_waveform): Drawing waveform from 0 with 0x zoom...
DEBUG:backend.c:454:(backend_rx_raw_loop): Timeout (1000)
DEBUG:backend.c:378:(backend_init): Stopping device...
DEBUG:connector.c:132:(connector_init_backend): Connector elektron matches the device
DEBUG:connector.c:183:(connector_init_backend): Testing elektron connector...
DEBUG:backend_alsa.c:205:(backend_tx_sysex_internal): Raw message sent (13): f0 00 20 3c 10 00 00 00 00 00 00 01 f7
DEBUG:connectors/elektron.c:751:(elektron_tx): Message sent (5): 00 00 00 00 01
DEBUG:backend.c:454:(backend_rx_raw_loop): Timeout (1000)
DEBUG:connector.c:183:(connector_init_backend): Testing microbrute connector...
DEBUG:backend_alsa.c:205:(backend_tx_sysex_internal): Raw message sent (6): f0 7e 7f 06 01 f7
DEBUG:backend.c:454:(backend_rx_raw_loop): Timeout (1000)
DEBUG:backend.c:116:(backend_midi_handshake): No MIDI identity reply
DEBUG:connector.c:183:(connector_init_backend): Testing phatty connector...
DEBUG:backend_alsa.c:205:(backend_tx_sysex_internal): Raw message sent (6): f0 7e 7f 06 01 f7
DEBUG:backend.c:454:(backend_rx_raw_loop): Timeout (1000)
DEBUG:backend.c:116:(backend_midi_handshake): No MIDI identity reply
DEBUG:connector.c:183:(connector_init_backend): Testing summit connector...
DEBUG:backend_alsa.c:205:(backend_tx_sysex_internal): Raw message sent (6): f0 7e 7f 06 01 f7
DEBUG:backend.c:454:(backend_rx_raw_loop): Timeout (1000)
DEBUG:backend.c:116:(backend_midi_handshake): No MIDI identity reply
DEBUG:connector.c:183:(connector_init_backend): Testing cz connector...
DEBUG:backend_alsa.c:205:(backend_tx_sysex_internal): Raw message sent (10): f0 44 00 00 70 10 60 70 31 f7
DEBUG:backend.c:454:(backend_rx_raw_loop): Timeout (1000)
DEBUG:connector.c:183:(connector_init_backend): Testing sds connector...
DEBUG:backend_alsa.c:205:(backend_tx_sysex_internal): Raw message sent (6): f0 7e 00 7d 00 f7
DEBUG:backend_alsa.c:205:(backend_tx_sysex_internal): Raw message sent (13): f0 00 20 3c 10 00 00 00 00 00 00 01 f7
DEBUG:connectors/elektron.c:751:(elektron_tx): Message sent (5): 00 00 00 00 01
DEBUG:backend.c:454:(backend_rx_raw_loop): Timeout (1000)
DEBUG:backend.c:685:(backend_rx_drain): Draining buffers...
DEBUG:backend.c:454:(backend_rx_raw_loop): Timeout (1000)
DEBUG:backend_alsa.c:205:(backend_tx_sysex_internal): Raw message sent (21): f0 7e 00 01 68 07 00 00 00 00 00 00 00 00 00 00 00 00 00 00 f7
DEBUG:backend.c:454:(backend_rx_raw_loop): Timeout (2000)
DEBUG:connector.c:183:(connector_init_backend): Testing efactor connector...
DEBUG:backend_alsa.c:205:(backend_tx_sysex_internal): Raw message sent (6): f0 7e 7f 06 01 f7
DEBUG:backend.c:454:(backend_rx_raw_loop): Timeout (5000)
DEBUG:connector.c:183:(connector_init_backend): Testing default connector...
DEBUG:backend_alsa.c:205:(backend_tx_sysex_internal): Raw message sent (6): f0 7e 7f 06 01 f7
DEBUG:backend.c:454:(backend_rx_raw_loop): Timeout (1000)
DEBUG:backend.c:116:(backend_midi_handshake): No MIDI identity reply
DEBUG:connector.c:192:(connector_init_backend): Using default connector...
DEBUG:progress.c:60:(progress_stop_running_sysex): Stopping SysEx transfer...
DEBUG:progress.c:41:(progress_join_thread): Stopping SysEx thread...
DEBUG:sample.c:492:(sample_set_sample_info): Loop start at 3044, loop end at 3044
DEBUG:sample.c:492:(sample_set_sample_info): Loop start at 6074, loop end at 6074
DEBUG:sample.c:492:(sample_set_sample_info): Loop start at 14361, loop end at 14361
DEBUG:sample.c:492:(sample_set_sample_info): Loop start at 28722, loop end at 28722
DEBUG:sample.c:492:(sample_set_sample_info): Loop start at 54524, loop end at 54524
DEBUG:sample.c:492:(sample_set_sample_info): Loop start at 6280, loop end at 6280
DEBUG:sample.c:492:(sample_set_sample_info): Loop start at 6847, loop end at 6847
DEBUG:sample.c:492:(sample_set_sample_info): Loop start at 28596, loop end at 28596
DEBUG:sample.c:492:(sample_set_sample_info): Loop start at 28631, loop end at 28631
DEBUG:sample.c:492:(sample_set_sample_info): Loop start at 4424, loop end at 4424
DEBUG:browser.c:620:(browser_load_dir): Browser already loading. Skipping load...
DEBUG:sample.c:492:(sample_set_sample_info): Loop start at 5675, loop end at 5675
DEBUG:sample.c:492:(sample_set_sample_info): Loop start at 6331, loop end at 6331
DEBUG:browser.c:620:(browser_load_dir): Browser already loading. Skipping load...
DEBUG:sample.c:492:(sample_set_sample_info): Loop start at 3828, loop end at 3828
DEBUG:browser.c:620:(browser_load_dir): Browser already loading. Skipping load...
DEBUG:sample.c:492:(sample_set_sample_info): Loop start at 28869, loop end at 28869
DEBUG:sample.c:492:(sample_set_sample_info): Loop start at 5251, loop end at 5251
DEBUG:browser.c:620:(browser_load_dir): Browser already loading. Skipping load...
DEBUG:sample.c:492:(sample_set_sample_info): Loop start at 28762, loop end at 28762
DEBUG:browser.c:620:(browser_load_dir): Browser already loading. Skipping load...
DEBUG:sample.c:492:(sample_set_sample_info): Loop start at 6591, loop end at 6591
DEBUG:sample.c:492:(sample_set_sample_info): Loop start at 6271, loop end at 6271
DEBUG:browser.c:620:(browser_load_dir): Browser already loading. Skipping load...
DEBUG:sample.c:492:(sample_set_sample_info): Loop start at 7164, loop end at 7164
DEBUG:browser.c:620:(browser_load_dir): Browser already loading. Skipping load...
DEBUG:sample.c:492:(sample_set_sample_info): Loop start at 28707, loop end at 28707
DEBUG:sample.c:492:(sample_set_sample_info): Loop start at 54858, loop end at 54858
DEBUG:sample.c:492:(sample_set_sample_info): Loop start at 27777, loop end at 27777
DEBUG:sample.c:492:(sample_set_sample_info): Loop start at 4341, loop end at 4341
DEBUG:sample.c:492:(sample_set_sample_info): Loop start at 3674, loop end at 3674
DEBUG:elektroid.c:2352:(elektroid_fill_fs_combo_bg): Selecting first filesystem...
DEBUG:sample.c:492:(sample_set_sample_info): Loop start at 48067, loop end at 48067
DEBUG:sample.c:492:(sample_set_sample_info): Loop start at 2950, loop end at 2950
DEBUG:editor.c:645:(editor_stop_load_thread): Stopping load thread...
DEBUG:sample.c:492:(sample_set_sample_info): Loop start at 7059, loop end at 7059
DEBUG:sample.c:492:(sample_set_sample_info): Loop start at 14450, loop end at 14450
DEBUG:sample.c:492:(sample_set_sample_info): Loop start at 6858, loop end at 6858
DEBUG:notifier.c:32:(notifier_set_dir): Changing local browser path to '/home/roby/Music/Samples/drums/Roland Tr-707'...
DEBUG:audio.c:274:(audio_reset_sample): Resetting sample...
DEBUG:browser.c:620:(browser_load_dir): Browser already loading. Skipping load...
DEBUG:notifier.c:150:(notifier_set_active): Stopping remote notifier...
DEBUG:notifier.c:103:(notifier_run): Finishing notifier...
DEBUG:notifier.c:32:(notifier_set_dir): Changing local browser path to '/home/roby/Music/Samples/drums/Roland Tr-707'...
```
![image](https://github.com/dagargo/elektroid/assets/107824400/2c3b851e-5034-450f-9a5f-a0f883f73ab4)

**Comment by dagargo** [comment]
This section is the interesting part. Let's break it in pieces.

Here, the `elektron` connector regex matches the system device name but the _modern_ handshake doesn't work as it's quite an old machine.

```
DEBUG:connector.c:132:(connector_init_backend): Connector elektron matches the device
DEBUG:connector.c:183:(connector_init_backend): Testing elektron connector...
DEBUG:backend_alsa.c:205:(backend_tx_sysex_internal): Raw message sent (13): f0 00 20 3c 10 00 00 00 00 00 00 01 f7
DEBUG:connectors/elektron.c:751:(elektron_tx): Message sent (5): 00 00 00 00 01
DEBUG:backend.c:454:(backend_rx_raw_loop): Timeout (1000)
```

As this fails, other connectors are tested. But fail too.

```
DEBUG:connector.c:183:(connector_init_backend): Testing microbrute connector...
DEBUG:backend_alsa.c:205:(backend_tx_sysex_internal): Raw message sent (6): f0 7e 7f 06 01 f7
DEBUG:backend.c:454:(backend_rx_raw_loop): Timeout (1000)
DEBUG:backend.c:116:(backend_midi_handshake): No MIDI identity reply
DEBUG:connector.c:183:(connector_init_backend): Testing phatty connector...
DEBUG:backend_alsa.c:205:(backend_tx_sysex_internal): Raw message sent (6): f0 7e 7f 06 01 f7
DEBUG:backend.c:454:(backend_rx_raw_loop): Timeout (1000)
DEBUG:backend.c:116:(backend_midi_handshake): No MIDI identity reply
DEBUG:connector.c:183:(connector_init_backend): Testing summit connector...
DEBUG:backend_alsa.c:205:(backend_tx_sysex_internal): Raw message sent (6): f0 7e 7f 06 01 f7
DEBUG:backend.c:454:(backend_rx_raw_loop): Timeout (1000)
DEBUG:backend.c:116:(backend_midi_handshake): No MIDI identity reply
DEBUG:connector.c:183:(connector_init_backend): Testing cz connector...
DEBUG:backend_alsa.c:205:(backend_tx_sysex_internal): Raw message sent (10): f0 44 00 00 70 10 60 70 31 f7
DEBUG:backend.c:454:(backend_rx_raw_loop): Timeout (1000)
```

Here, during the `sds` connector handshake, everything fails, including an additional check for Elektron devices supporting SDS.

```
DEBUG:connector.c:183:(connector_init_backend): Testing sds connector...
DEBUG:backend_alsa.c:205:(backend_tx_sysex_internal): Raw message sent (6): f0 7e 00 7d 00 f7
DEBUG:backend_alsa.c:205:(backend_tx_sysex_internal): Raw message sent (13): f0 00 20 3c 10 00 00 00 00 00 00 01 f7
DEBUG:connectors/elektron.c:751:(elektron_tx): Message sent (5): 00 00 00 00 01
DEBUG:backend.c:454:(backend_rx_raw_loop): Timeout (1000)
DEBUG:backend.c:685:(backend_rx_drain): Draining buffers...
DEBUG:backend.c:454:(backend_rx_raw_loop): Timeout (1000)
DEBUG:backend_alsa.c:205:(backend_tx_sysex_internal): Raw message sent (21): f0 7e 00 01 68 07 00 00 00 00 00 00 00 00 00 00 00 00 00 00 f7
DEBUG:backend.c:454:(backend_rx_raw_loop): Timeout (2000)
```

Another connector here...

```
DEBUG:connector.c:183:(connector_init_backend): Testing efactor connector...
DEBUG:backend_alsa.c:205:(backend_tx_sysex_internal): Raw message sent (6): f0 7e 7f 06 01 f7
DEBUG:backend.c:454:(backend_rx_raw_loop): Timeout (5000)
```

After all of these, the default connector fails to determine the device too but it's the one being selected.

```
DEBUG:connector.c:183:(connector_init_backend): Testing default connector...
DEBUG:backend_alsa.c:205:(backend_tx_sysex_internal): Raw message sent (6): f0 7e 7f 06 01 f7
DEBUG:backend.c:454:(backend_rx_raw_loop): Timeout (1000)
DEBUG:backend.c:116:(backend_midi_handshake): No MIDI identity reply
DEBUG:connector.c:192:(connector_init_backend): Using default connector...
```

But there is something really weird here. There is no response for the Identity Request Universal SysEx message (`f0 7e 7f 06 01 f7`). It's all timeouts.

Can you use the `sds` connector from the CLI? Or have you just used the send SysEx functionality? I thought the detection of the Machinedrum was working at some point. Can you by any chance try to connect the Machinedrum without the TM-1?

By the way, in the right lower corner you can find the detected device. It's just the default.

**Comment by erroreyes** [comment]
> Can you use the sds connector from the CLI?

I admit that I am confused about the command line implementation and I am not really sure what commands and options to issue in the terminal. If you don't mind, could you give me a few sample command lines to try out?

> Or have you just used the send SysEx functionality?

I just sent a Sysex firmware file through the TM-1 and the Machinedrum is receiving it.

> Can you by any chance try to connect the Machinedrum without the TM-1?

Unfortunately I cannot at the moment since the TM-1 is the only MIDI interface I have on hand at the moment.

____

I am curious though, what is the UI expected to look like for a TM-1 + Machinedrum setup, or for a Machinedrum connected to any other MIDI interface? What functionality should be made available in the UI once a connection is made? Is the expectation to send a Sysex dump of samples or SDS files? Can individual SDS files be transmitted?

**Comment by dagargo** [comment]
> I just sent a Sysex firmware file through the TM-1 and the Machinedrum is receiving it.

Nice!

> I admit that I am confused about the command line implementation and I am not really sure what commands and options to issue in the terminal. If you don't mind, could you give me a few sample command lines to try out?

Then let's try to send a sample from the CLI.

First, list the devices. From version 3.0, the device 0 is always the computer. In my case, device 1 is a MIDI to USB interface hooked up to my E-mu ESI-2000.

```
$ elektroid-cli ld
0: id: SYSTEM_ID; name: asuka
1: id: hw:1,0,0; name: hw:1,0,0: M-Audio MIDISPORT Uno, M-Audio MIDISPORT Uno MIDI 1
```

Let's try to guess what's in there by running the command `info`. It'll take a while as it will check all the connectors. In my case, the `sds` connector handshake succeeds and returns the initialized values. This won't work in your case as we already know something happens with the handshake, or will it?

```
$ elektroid-cli info 1
Type: MIDI
Device name: SDS sampler
Device version: 
Device description: 
Connector name: sds
Filesystems: program,16bits1c,14bits1c,12bits1c,8bits1c,44.1k16b1c,32k16b1c,16k16b1c,8k16b1c
```

Anyway, let's try to send a sample.
All the commands have the same form: `connector-fs-operation`. In this case, we are using the `sds` connector, the 16 bits and sample rate as stored in the file, and the `upload` operation.

```
$ elektroid-cli -vv sds-16bits1c-ul sample.wav 1:/1:name
```

Does that work? Could you post the output of the last command here? Note that you might need to use other filesystem. Isn't the Machinedrum 12 bits? In fact, perhaps this is the issue.

I decided to implement the handshake for SDS devices by sending a dump header and listening for a reply. This header contains the bit depth of the sample to be sent.

This is the line.

https://github.com/dagargo/elektroid/blob/9f46c3b42ea9dcee18c478e83e4f38525eca530e/src/connectors/sds.c#L1235

Does it make any difference if you change that 16 with a 12 and recompile? Would the `info` command work then?

**Comment by dagargo** [comment]
> I am curious though, what is the UI expected to look like for a TM-1 + Machinedrum setup, or for a Machinedrum connected to any other MIDI interface?

The GUI should look the same. Depending on the filesystem selected on the device side, on the computer side are shown only the appropriate files. In the case of SDS devices, you should see samples there. And in this case, the sampler editor will be shown too.

> What functionality should be made available in the UI once a connection is made? Is the expectation to send a Sysex dump of samples or SDS files?

You'll just be able to drag and drop samples from left to right to certain slot. All the needed conversions will apply.

> Can individual SDS files be transmitted?

You wouldn't work with SDS files but with actual samples.

If you wanted to send SDS files, which are just a bunch of SysEx messages, you'd need to use the menu. You could send several SysEx files at once. Just be reminded that you'd have no control over the slot they'd have been sent to. How a device will handle this depends on the particular case.

**Comment by erroreyes** [comment]
```
❯ elektroid-cli ld
0: id: SYSTEM_ID; name: rb-linux
1: id: hw:1,0,0; name: hw:1,0,0: Elektron TM-1, Elektron TM-1 MIDI 1
```

Calling `info` in the TM-1 returns a connector name of `default`, most likely after all the timeouts, and only displays `program` as file system, which explains why the UI only shows the "Program" option in the drop down menu.

```
❯ elektroid-cli info 1
Type: MIDI
Device name: MIDI device
Device version: 
Device description: 
Connector name: default
Filesystems: program
```

I am assuming that because the only file system available is `program`, sending a file fails; the `sds-16bits1c-ul` is not available:

```
❯ elektroid-cli -vv sds-16bits1c-ul ~/Music/Samples/sqr_wv.wav 1:/1:default
DEBUG:elektroid-cli.c:830:(main): Connector: "sds"; filesystem: "16bits1c"; operation: "ul"
DEBUG:backend_alsa.c:363:(backend_get_system_subdevices): Adding hw:1 (name 'Elektron TM-1', subname 'Elektron TM-1 MIDI 1')...
DEBUG:backend.c:367:(backend_init): Initializing backend (ALSA) to 'hw:1,0,0'...
DEBUG:backend_alsa.c:85:(backend_init_int): Setting blocking mode...
DEBUG:backend.c:685:(backend_rx_drain): Draining buffers...
DEBUG:backend.c:454:(backend_rx_raw_loop): Timeout (1000)
DEBUG:backend.c:378:(backend_init): Stopping device...
DEBUG:connector.c:132:(connector_init_backend): Connector elektron matches the device
DEBUG:connector.c:171:(connector_init_backend): Testing sds connector...
DEBUG:backend_alsa.c:205:(backend_tx_sysex_internal): Raw message sent (6): f0 7e 00 7d 00 f7
DEBUG:backend_alsa.c:205:(backend_tx_sysex_internal): Raw message sent (13): f0 00 20 3c 10 00 00 00 00 00 00 01 f7
DEBUG:connectors/elektron.c:751:(elektron_tx): Message sent (5): 00 00 00 00 01
DEBUG:backend.c:454:(backend_rx_raw_loop): Timeout (1000)
DEBUG:backend.c:685:(backend_rx_drain): Draining buffers...
DEBUG:backend.c:454:(backend_rx_raw_loop): Timeout (1000)
DEBUG:backend_alsa.c:205:(backend_tx_sysex_internal): Raw message sent (21): f0 7e 00 01 68 07 00 00 00 00 00 00 00 00 00 00 00 00 00 00 f7
DEBUG:backend.c:454:(backend_rx_raw_loop): Timeout (2000)
DEBUG:backend.c:389:(backend_destroy): Destroying backend...
ERROR:elektroid-cli.c:894:(main): Error: No such device
```

In the File Sample Manager, the Machinedrum waits for a sample, I send the commend from the terminal, the MD waits a bit, and then "cancels" the transmission (displays "CANCELLED" on the screen).

> Isn't the Machinedrum 12 bits? In fact, perhaps this is the issue.

16 bit samples can be transferred to the Machinedrum and they are converted internally to 12-bit. I can send 16-bit WAV and SDS files with `amidi` and they get converted.

**Comment by dagargo** [comment]
> Calling info in the TM-1 returns a connector name of default, most likely after all the timeouts, and only displays program as file system, which explains why the UI only shows the "Program" option in the drop down menu.

Exactly. That is by design. The GUI won't be able to do anything special but will allow selecting presets and sending and receiving SysEx.

> I am assuming that because the only file system available is program, sending a file fails; the sds-16bits1c-ul is not available:

You're right.

However, notice the CLI bypasses the connector detection stage and uses the connector indicated by the user. What happens after is that the chosen connector runs the handshake anyway and it fails because no messages are received.

> 16 bit samples can be transferred to the Machinedrum and they are converted internally to 12-bit. I can send 16-bit WAV and SDS files with amidi and they get converted.

So 16 bits is OK.

> In the File Sample Manager, the Machinedrum waits for a sample, I send the commend from the terminal, the MD waits a bit, and then "cancels" the transmission (displays "CANCELLED" on the screen).

Is the Machinedrum showing something on the screen during the connector detection or handshake?

I suspect the issue is just that no packages are received. Is the computer receiving MIDI data from the Machinedrum? You said that sending SysEx works, can you use `amidi` to check if it's receiving anything?

**Comment by erroreyes** [comment]
> Is the Machinedrum showing something on the screen during the connector detection or handshake?

When it is in the file manager and I select the sample slot to receive a sample to, the only thing that shows is CANCELLED after the  connector routine fails. When the Machinedrum is not in the file manager and its normal view, it displays the message "ERROR INVALID POSITION". That made me think that maybe the syntax for the path was wrong so I tried:
```
elektroid-cli -vv sds-16bits1c-ul ~/Music/Samples/sqr_wv.wav 1:/44:sqr
```
assuming that 1 is the device, 44 is the sample slot position in the Machinedrum where I want a new sample to be stored, and `sqr` is the name of I want to give to the sample, but that didn't work either.

**Comment by dagargo** [comment]
> When it is in the file manager and I select the sample slot to receive a sample to, the only thing that shows is CANCELLED after the connector routine fails. 

You don't need to setup anything on the SDS devices. The whole process is controlled from the computer.

> I can receive data from the Machinedrum to the laptop with amidi.

Great.

> When the Machinedrum is not in the file manager and its normal view, it displays the message "ERROR INVALID POSITION". That made me think that maybe the syntax for the path was wrong so I tried:

Then, the issue is in the handshake message and no matter what parameters you pass the handshake will be the same.

But you guessed out all the parameters correctly.

The issue is very likely in the line 1235. At least I added a meaningful comment.

Change the `1000` value for `44`, which is the slot you were using but any other would do. Recompile and test the CLI again. Does this make any difference?

https://github.com/dagargo/elektroid/blob/9f46c3b42ea9dcee18c478e83e4f38525eca530e/src/connectors/sds.c#L1233-L1248

**Comment by erroreyes** [comment]
I started a fork. 

After I changed the value to 44 and issued

```
elektroid-cli -vvv sds-16bits1c-ul audio.wav 1:/44:sqr 
```

I now get an "ERROR INVALID SMPL RATE" error on the Machinedrum.

**Comment by dagargo** [comment]
> I now get an "ERROR INVALID SMPL RATE" error on the Machinedrum. The audio.wav file is in 16-bit, 44.1kHz. For comparison, I can convert that to SDS, transfer it via amidi, and it loads in the MD without issues.

We're getting closer.

Let's keep in mind that the SDS connector has only been tested on my ESI-2000 and probably there will be bugs. Also, this was my attempt at detecting the SDS feature and might not work with other devices and might need to be redesigned.

The issue is now on the samplerate, which is not initialized. Same line as before.

https://github.com/dagargo/elektroid/blob/9f46c3b42ea9dcee18c478e83e4f38525eca530e/src/connectors/sds.c#L1235

This creates a mock message to test if the device responds as an SDS sampler would.

The 3rd parameter is `NULL`, so it doesn't initialize properly the message, including the sample rate.

https://github.com/dagargo/elektroid/blob/9f46c3b42ea9dcee18c478e83e4f38525eca530e/src/connectors/sds.c#L258-L285

Try passing an initialized `struct sample_info *` value.

**Comment by erroreyes** [comment]
I think I created the struct correctly (I'm not a C/C++ person):

```c
struct sample_info *si;
si->rate = 44100;
si->channels = 1;
tx_msg = sds_get_dump_msg (44, 0, si, 16);
```

When I send the command line, I don't get the error message. I think we are on to something like you said

```
❯ elektroid-cli -vvv sds-16bits1c-ul audio.wav 1:/44:sqr
DEBUG:elektroid-cli.c:830:(main): Connector: "sds"; filesystem: "16bits1c"; operation: "ul"
DEBUG:backend_alsa.c:363:(backend_get_system_subdevices): Adding hw:1 (name 'Elektron TM-1', subname 'Elektron TM-1 MIDI 1')...
DEBUG:backend.c:367:(backend_init): Initializing backend (ALSA) to 'hw:1,0,0'...
DEBUG:backend_alsa.c:85:(backend_init_int): Setting blocking mode...
DEBUG:backend.c:685:(backend_rx_drain): Draining buffers...
DEBUG:backend.c:454:(backend_rx_raw_loop): Timeout (1000)
DEBUG:backend.c:378:(backend_init): Stopping device...
DEBUG:connector.c:132:(connector_init_backend): Connector elektron matches the device
DEBUG:connector.c:171:(connector_init_backend): Testing sds connector...
DEBUG:backend_alsa.c:205:(backend_tx_sysex_internal): Raw message sent (6): f0 7e 00 7d 00 f7
DEBUG:backend_alsa.c:205:(backend_tx_sysex_internal): Raw message sent (13): f0 00 20 3c 10 00 00 00 00 00 00 01 f7
DEBUG:connectors/elektron.c:751:(elektron_tx): Message sent (5): 00 00 00 00 01
DEBUG:backend.c:454:(backend_rx_raw_loop): Timeout (1000)
DEBUG:backend.c:685:(backend_rx_drain): Draining buffers...
DEBUG:backend.c:454:(backend_rx_raw_loop): Timeout (1000)
fish: Job 1, 'elektroid-cli -vvv sds-16bits1c…' terminated by signal SIGSEGV (Address boundary error)
```

Is `Raw message sent (6): f0 7e 00 7d 00 f7` the Sysex init message for the ESI?

**Comment by dagargo** [comment]
You're using a pointer that has not been initialized, hence the `SIGSEGV`.

```
struct sample_info *si;
si->rate = 44100;
si->channels = 1;
tx_msg = sds_get_dump_msg (44, 0, si, 16);
```

You should have done it this way. (The memory is allocated in the stack and you can pass a pointer to it to other functions.)

```
struct sample_info si;
si.rate = 44100;
si.channels = 1;
tx_msg = sds_get_dump_msg (44, 0, &si, 16);
```

Anyway, I have pushed a commit to try to improve all this. Now, 3 different handshake methods are used and the original one is now the fallback, as it's very tricky. I can not tell if this will work on the Machinedrum.

In case it wouldn't, we could try to look for a SysEx request that the Machinedrum implements and use the reply to detect this. The Kit Sysex Dump commented [here](https://cycling74.com/forums/machinedrum-sysex) looks promising for this purpose. The https://github.com/jmamma/MCL repo might have something interesting too.

So, is the last commit fixing the Machinedrum detection?

**Comment by dagargo** [comment]
Oops... I forgot to answer this.

> Is Raw message sent (6): f0 7e 00 7d 00 f7 the Sysex init message for the ESI?

That's the MIDI inquiry message. It''s the official way to ask what device is there. But not all devices implement this.

Elektroid tries this first because an official response would be the best way to ensure what's the actual device but even modern machines do no reply to this message. For instance, all the modern Elektron machines. And, as seen in the log, the TM-1/Machinedrum does not do this either.
If the MIDI inquiry request fails, then the different connectors could try different approaches to identify the devices these work with.

This is the code of a simple handshake function that relies purely on the result of the MIDI inquiry request. (Internally, some fields are set so only some checks need to be done.)

https://github.com/dagargo/elektroid/blob/35ca06be3b04fe9b9ee5288866d546b79d1675d7/src/connectors/microbrute.c#L505-L527

The handshake functions in the `sds` connector is really tricky because it's quite difficult to guess if the device implements the SDS standard. That's what I tried to improve in the last commit when adding other checks in it.

**Comment by erroreyes** [comment]
Sorry for the gap in response. I need to make that fix to my branch/fork, but for now, I just git pull your latest changes, built on them, and ran `elektroid-cli -vv sds-16bits1c-ul ~/Music/Samples/sqr_wv.wav 1:/1:default ` and this is the result I got:

```bash
DEBUG:elektroid-cli.c:829:(main): Connector: "sds"; filesystem: "16bits1c"; operation: "ul"
DEBUG:backend_alsa.c:363:(backend_get_system_subdevices): Adding hw:1 (name 'Elektron TM-1', subname 'Elektron TM-1 MIDI 1')...
DEBUG:backend.c:367:(backend_init): Initializing backend (ALSA) to 'hw:1,0,0'...
DEBUG:backend_alsa.c:85:(backend_init_int): Setting blocking mode...
DEBUG:backend.c:685:(backend_rx_drain): Draining buffers...
DEBUG:backend.c:454:(backend_rx_raw_loop): Timeout (1000)
DEBUG:backend.c:378:(backend_init): Stopping device...
DEBUG:connector.c:132:(connector_init_backend): Connector elektron matches the device
DEBUG:backend_alsa.c:205:(backend_tx_sysex_internal): Raw message sent (6): f0 7e 7f 06 01 f7
DEBUG:backend.c:454:(backend_rx_raw_loop): Timeout (1000)
DEBUG:backend.c:116:(backend_midi_handshake): No MIDI identity reply
DEBUG:connector.c:173:(connector_init_backend): Testing sds connector...
DEBUG:backend_alsa.c:205:(backend_tx_sysex_internal): Raw message sent (6): f0 7e 00 7d 00 f7
DEBUG:backend_alsa.c:205:(backend_tx_sysex_internal): Raw message sent (13): f0 00 20 3c 10 00 00 00 00 00 00 01 f7
DEBUG:connectors/elektron.c:751:(elektron_tx): Message sent (5): 00 00 00 00 01
DEBUG:backend.c:454:(backend_rx_raw_loop): Timeout (1000)
DEBUG:backend.c:685:(backend_rx_drain): Draining buffers...
DEBUG:backend.c:454:(backend_rx_raw_loop): Timeout (1000)
DEBUG:backend_alsa.c:205:(backend_tx_sysex_internal): Raw message sent (8): f0 7e 00 05 04 01 00 f7
DEBUG:backend.c:454:(backend_rx_raw_loop): Timeout (1500)
DEBUG:backend_alsa.c:205:(backend_tx_sysex_internal): Raw message sent (10): f0 7e 00 05 02 01 00 01 00 f7
DEBUG:backend.c:454:(backend_rx_raw_loop): Timeout (1500)
DEBUG:backend_alsa.c:205:(backend_tx_sysex_internal): Raw message sent (21): f0 7e 00 01 68 07 00 00 00 00 00 00 00 00 00 00 00 00 00 00 f7
DEBUG:backend.c:454:(backend_rx_raw_loop): Timeout (2000)
DEBUG:backend.c:389:(backend_destroy): Destroying backend...
ERROR:elektroid-cli.c:893:(main): Error: No such device
```
where `ERROR:elektroid-cli.c:893:(main): Error: No such device` is a new error message.

I still get the "CANCELLED" message when I put the MD to receive a sample and issue that `elektroid-cli` command send a sample.

**Comment by dagargo** [comment]
> I still get the "CANCELLED" message when I put the MD to receive a sample and issue that elektroid-cli command send a sample.

We don't need to do that. Sample transmission is always started by Elektroid. We had to check if the sent messages were breaking the communication and so it was but it is a requirement that the receiving sample state is *not* activated during Elektroid handshake process.

So... We haven't fixed anything. Let's try something different.

As the problem is detecting the MD, we just need a message that identifies this particular machine and the best way to test different messages is with the `amidi` command.

This is an example of a preset download with an Arturia MicroFreak.

```
$ amidi -l
Dir Device    Name
IO  hw:0,0,0  Arturia MicroFreak Arturia Micr

$ amidi -p hw:0,0,0 -S "f0 00 20 6b 07 01 00 03 19 00 00 00 f7" -d -t 3
F0 00 20 6B 07 01 00 23 52 00 00 00 00 00 00 00 00 00 00 02 10 4E 65 72 76 6F 75 73 4B 65 79 73 00 00 00 00 00 00 00 00 00 00 00 00 F7
45 bytes read
```

If there is a response and it matches the expected data, then there is a MicroFreak. What we need to do is finding a message that fulfills these requirements.

From the [official MD manual](https://www.polynominal.com/elektron-Machinedrum-sps1/machinedrum-sps1-manual.pdf).

```

**Comment by erroreyes** [comment]
Here you go:

```fish
❯ amidi -p hw:1,0,0 -S "f0 00 20 3c 02 00 51 00 f7" -d -t 3

F0 00 20 3C 04 00 02 01 F7
F0 00 20 3C 02 00 50 06 01 00 06 06 06 06 06 06 06 06 06 06 06 06 06 06 06 06 7F 7F 7F 7F 7F 7F 7F 7F 7F 7F 7F 7F 7F 7F 7F 7F 7F 7F 7F 7F 7F 7F 7F 7F 7F 7F 7F 7F 7F 7F 7F 7F 7F 7F 7F 7F 7F 7F 7F 7F 54 7F 00 7F 01 7F 02 03 54 7F 04 7F 05 7F 06 07 52 7F 08 7F 09 0A 7F 0B 52 7F 0C 7F 0D 0E 7F 0F 4A 7F 10 11 7F 12 7F 13 4A 7F 14 15 7F 16 7F 17 2A 18 7F 19 7F 1A 7F 1B 29 1C 7F 1D 7F 1E 1F 7F 7F 7F 7F 7F 7F 7F 7F 7F 7F 7F 7F 7F 7F 7F 7F 7F 7F 7F 7F 7F 7F 7F 7F 7F 7F 7F 7F 7F 7F 7F 7F 7F 7F 7F 7F 7F 7F 7F 7F 7F 60 7F 7F 7F 00 11 13 01 61 01 10 10 01 01 00 00 00 00 7F 7F 00 01 77 20 01 3B F7
206 bytes read
```

**Comment by dagargo** [comment]
The first message is interesting. Looks like it is the TM-1 responding based on the information from [this Elektronauts post](https://www.elektronauts.com/t/megacommand-minicommand-resurrection-mclive/27805/78). By the way, there are lots of speed negotiation information there.

Considering that there we have the SysEx messages for globals, kits and other types of data, I'm considering creating a new connector so it would be easier to add new functionalities there.

**Comment by dagargo** [comment]
A new branch called `machinedrum` includes the code to work with the MD samples. Both GUI and CLI should work but the connector has not been tested.

Anyway, this is a starting point.

A few notes:
* The connector is called `machinedrum`.
* The filesystem for samples is called `sample`.
* All the internal functionality has been tested but the renaming operation.
* Adding a filesystem for the global settings looks really easy. We could try to implement this if you want.
* The sample amount limit and the sample name length can be tweaked from these constants.

https://github.com/dagargo/elektroid/blob/f323db2d18f82dff03e777eba94775a435477424/src/connectors/machinedrum.c#L25-L26

Could you post here the output of these commands?

```
$ elektroid-cli -vv info 1

$ elektroid-cli -vv machinedrum-sample-ls | head
```

So, is this working for you?

**Comment by dagargo** [comment]
I forgot to mention that getting the sample names could be possible.

As with the renaming functionality, this code is already implemented but has never been tested.

If you're interested check if this works.

```
$ amidi -p hw:1,0,0 -S "f0 7e 00 05 04 00 00 f7" -d -t 3
```

**Comment by dagargo** [comment]
@erroreyes, did you manage to try the `machinedrum` branch?

We are not in a hurry, it's just that wanted to track the status of this issue. Don't mean to put pressure on you.

If,.for.whatecer reason, you can't work on this we might ask in Elektronauts if anyone else is interested.

**Comment by johnnywagner** [comment]
I've got 2 working TM-1's, a Machinedrum & Monomachine and would be happy to help test this as C6 is getting harder for everyone to use. I'm not familiar with autotools though, is it possible to compile for Windows or Mac? Or would I need to set up a VM to run this?

**Comment by dagargo** [comment]
Thanks for wanting to try this.

First, a bit of a recap.

* Basic sample transmission should already work with the MachineDrum. The code resides in its own branch.
* Additional things like renaming are still in the works.
* Turbo MIDI, from the application side, seems to work but it's still unknown if something else needs to be done to work in the turbo mode. There are some notes about all these in the previous comments.

Regarding the compilation, there are many options.

* Last Tuesday I checked the Windows compilation **under MSYS2 UCRT64** and added a few commits to address some minor issues. Now, seems to work nicely but the MSYS2 layer makes it very slow and compiling and running it's not really user friendly.
* Elektroid should compile and work under OSX and autotools.
* The development environment and where Elektroid has been fully tested is GNU/Linux. I could help you easily if we choice this path.

Perhaps, the best choice now is going for a Linux VM and, once it's done, then we could create a new issue to help you building this on OSX.

Is this good for you?

If it is, let's follow this.

1. Install a Debian or Ubuntu VM. (I've tried WSL on Windows and works quite well too. This is another option.)
2. Clone the repo and change to the `machinedrum` branch.
3. Install the dependencies indicated from the instructions.
4. Try running the compilation instructions.
5. Run Elektroid (you'll need to map the USB devices to the guest OS in your VM manager).

Let me know at which point you are so I can help you with that.

**Comment by dagargo** [comment]
There is the issue #108 related to building on OSX.

**Comment by johnnywagner** [comment]
Sounds great, thanks for all of the info. It may be a few days before you hear back from me as I have never set up a Linux VM or build environment before but am eager to figure it out. Is this the comment thread an appropriate place to reach out for troubleshooting/help or should we move to some kind of direct messaging (if needed)?

**Comment by dagargo** [comment]
Take the time you need. This issue was created almost 2 years ago so we're definitely not in a hurry.

As a team, we've done as much as we could but we haven't accomplished much yet. Still, I think we are really close.

> Is this the comment thread an appropriate place to reach out for troubleshooting/help or should we move to some kind of direct messaging (if needed)?

I'd say so. If we end up cluttering this issue so much, we'll find another way.

**Comment by dagargo** [comment]
@johnnywagner, in case it makes things easier for you, support for OSX with Homebrew has been added.

**Comment by dagargo** [comment]
For anyone reading this, has there been any advance in this issue?

BTW, branch `machinedrum` is way behind master so I should probably reabase it.

**Comment by johnnywagner** [comment]
I haven't had a chance to test it yet but I haven't forgotten!

**Comment by adsr** [comment]
Hi, I'm a Linux user with a Machinedrum and can help test / debug. I misplaced my TM-1 a while ago but I will look for that.

I figured I'd try a non-turbo transfer on the `machinedrum` branch and that worked:

```console
$ ./elektroid-cli machinedrum-sample-ul ~/downloads/untitled.wav 1:/34:34
```

This uploaded untitled.wav to slot 35 (34 0-indexed). The name appears as "....". `machinedrum-sample-ls` also worked, showing 0 thru 127.

This helps me as Elektron C6 crashes under wine. Thanks!

Btw I needed the following to compile the `machinedrum` branch on my setup.

```diff
diff --git a/src/connectors/system.c b/src/connectors/system.c
index d2e5c83..098ad13 100644
--- a/src/connectors/system.c
+++ b/src/connectors/system.c
@@ -19,6 +19,7 @@
  */
 
 #include <errno.h>
+#include <glib/gstdio.h>
 #include <glib/gi18n.h>
 #if defined(__linux__)
 #include <sys/statvfs.h>
diff --git a/src/editor.c b/src/editor.c
index 4e8c017..2811ac0 100644
--- a/src/editor.c
+++ b/src/editor.c
@@ -19,6 +19,7 @@
  */
 
 #include <gtk/gtk.h>
+#include <glib/gstdio.h>
 #include <glib/gi18n.h>
 #include "editor.h"
 #include "sample.h"
```

You mentioned you need to rebase so maybe that's already fixed.

If I find my TM-1 I will test with that and update.

**Comment by dagargo** [comment]
This is great news!

TM-1 is something we can deal with later as this will only speed up the transfers.

Regarding sample names, we need to know how the machine names the samples. My guess is that they're using an extension of MIDI SDS for this so 've enabled it in the code.
Are the names there now? You should see the names in the GUI too.
Consider this naming feature has never been tested so there might be errors. The specifications are [here](http://www.somascape.org/midi/tech/spec.html#usx7E0503).

As you're saying the samples are 0-indexed, I've tried to fix it in the last commit.

Branch `machinedrum` has been rebased too. Those compilation errors were already fixed in `master`, just as you said.

Please, check everything again.

**Comment by dagargo** [comment]
Branch `machinedrum` have been rebased.

**Comment by dagargo** [comment]
Branch `machinedrum` has been rebased.

As no more functional changes in the connectors are expected for the next version (3.1), I'm starting to plan the release and I was wondering if anyone here has managed to test the `machinedrum` branch.

This issue has expanded in time for more than 2.5 years and although it is not a problem, many things have changed.
More specifically, the purpose of the issue has changed over time and the tittle of the issue does not represent the current goal.

Currently, the idea is to implement a connector for the Elektron Machinedrum.

The Elektron TM-1 has proven to be quite elusive and I consider we have very little and reliable information about it.
Regarding this, the idea was to try to activate the button via SysEx messages but this is a totally optional feature because the Machinedrum will work with Elektroid regardless of the TM-1 as any other USB-MIDI adapter will make it work.

**Comment by dagargo** [comment]
`master` branch has been tested and the code is release ready.

Branch `machinedrum` has been rebased.

A few connector options have been removed as they were redundant and the code has been updated.
Also, a missing configuration preventing the connector to work at all has been added.

**Comment by johnnywagner** [comment]
Sorry for my inactivity, I still need to learn how to compile this program to test it for you. It's on my agenda still.

In the mean time I did find this information someone wrote up on how the Monomachine DIGIPro files are structured:
https://gist.github.com/rumblesan/e520ae4099d0583e3ef4e228beabe2b3

Maybe Elektron used the same header formatting for samples on the MD. Hope this is helpful for now.

**Comment by dagargo** [comment]
Nice to know you're on it. :+1: 

Supposedly, the implementation is ready to be tested. I only need someone to confirm it actually works.

The sampling management is based on MIDI SDS (1-based indexing) and I believe it could support the sample renaming standard too.

There are 3 use cases to be tested.

* Upload a sample
* Download a sample
* Rename a sample

**Comment by dagargo** [comment]
Exactly.

I've just rebased the `machinedrum` branch to incorporate the latest changes from `master`.

**Comment by johnnywagner** [comment]
![image](https://github.com/user-attachments/assets/353ea4dc-af8e-44d2-a32a-7980b871e1ea)
Ok got everything set up and I don't think the UI is currently compatible with the Machinedrum. The Machinedrum cannot report its Samples in real time. I presume other Elektron boxes can do this (?) which is why there is no "Receive" button in Elektroid like there is in C6 to listen to the Machinedrum after the user instructs a SYSEX send. See this snippet from the manual below to maybe get a better idea of how this works:
![image](https://github.com/user-attachments/assets/7a7dda36-1ebd-4d1c-9a97-84bcf28193a5)

So while Elektroid seems to automatically start polling the synth for samples, the Machinedrum is reporting nothing as the user hasn't instructed the Machinedrum to send the data. While Elektroid was listening in my case, I set the Machinedrum to send the sample data but since it wasn't synced with Elektroid it all came through as garbled unlistenable data as seen in the screenshot above. 

Like @adsr above though, I was able to send a sample by dragging from the left column to the right column while the Machinedrum was set to RECV mode in the sample manager menu:
![image](https://github.com/user-attachments/assets/946af664-a434-4511-8d37-4f0acb33aa6b)

The sample came through great on the other end but two issues are present due to the differences in how the machinedrum works I talk about above:
1. As soon as you drag over the sample, it begins sending the entire wav to the Machinedrum. This doesn't allow the user any time to rename the sample obviously.
2. Once the sample is sent, Elektroid tries to reload the sample names, required the user to send garbled data again to have access to sending another sample.

So Ideally, you should create buttons for the Machine mode that allow the user to send and receive MIDI data, mirroring the functionality of C6.

Next up, while it is not available in the stock firmware, most power users like myself are running a custom firmware on the Machinedrum these days that allow the Machinedrum to report sample names, positions, and empty status. Below is a screenshot from the custom firmwares documentation. Incorporating this in Elektroid would let you bring the right column up to parity with how Elektroid functions for other samplers.
![image](https://github.com/user-attachments/assets/f3bb4560-8bdd-4fe8-9a0a-b23a3e2f5469)

You can get full documentation of the custom firmware from "Machinedrum_SPS1-UW_OS_X.11.zip" on the latest release:
https://github.com/jmamma/MCL/releases

Finally, I unfortunately report that the TM-1 turbo speeds are not working in the Machinedrum branch. I'm happy to help troubleshoot this though and help get it working as this is the main reason I want to use Elektroid one day.

Thanks! Hope this is helpful. Now that I have ubuntu set up in my Virtual machine I can help regularly test new versions and provide feedback. Maybe one day you can even fully implement the Monomachine :)

**Comment by dagargo** [comment]
Thanks for your detailed post!

A lot to unravel. I'll take a second read later.

Albeit the data being received, it looks like standard SDS name support is not working. We can easily disable this here.

https://github.com/dagargo/elektroid/blob/8638869ad4468e83c215af6911e3f1de64dba650/src/connectors/machinedrum.c#L161

Set this to FALSE and recompile.

If I've understood you well, uploading should work and listing too (without names). I fear that downloading will only be available on request. To do so, use the receive SysEx menu. But it will be a SysEx file and not a sample file. I'll think about this.

**Comment by johnnywagner** [comment]
Definitely please read it again later, I think that you maybe misunderstand the reason I got the garbled SDS name information in the right hand column.

To your second comment, yes downloading samples will only be available on request. **BUT,** if you incorporate the sysex sample slot query that is apart of MDX, you will be able to list **with the names** and sample locations currently on the Machinedrum to allow the user to more clearly see the changes they will be making upon pressing a potential "send" button that I suggested.

**Comment by dagargo** [comment]
I still haven't got the time to take a proper look at this.

But I've just came across this thread where there is a video of the uploading process and I think it's worth mention here.

https://www.elektronauts.com/t/transfer-samples-from-to-machinedrum/130337/19

**Comment by johnnywagner** [comment]
Yeah good find, that would probably be much more helpful than my written explanations of how it works. If you ever want me to video myself doing anything on any of my machines (monomachine, machinedrum, tm-1) let me know and I'll be happy to help.

**Comment by dagargo** [comment]
machinedrum branch has just been rebased to incorporate the latest changes from master.

**Comment by dagargo** [comment]
Sorry that's been such a long time.

Anyway, I've just pushed a commit to let users control the transfers. It's just a message that pops up and asks the user to perform some actions and let them continue or cancel from that point.

I don't like the solution much but it's the only thing we can do to overcome the fact that neither downloading nor uploading can be performed programmatically. This is something to be avoided if the hardware allows it.

This should work for both the GUI and the CLI.

I haven't been able to test the actual behavior but I've kind of simulated it and I think it might fix all the issues.

@johnnywagner, could you test this and let us know your thoughts?

**Comment by ianhundere** [comment]
@dagargo could i test for the monomachine ?

**Comment by dagargo** [comment]
Hi, @ianhundere!

It's been quite a long time since the `machinedrum` branch was changed so I've just rebased it and pushed the changes.

This branch implemented MIDI SDS for the Machinedrum, which follows the standard but requires the machine to select the target slot.

Does the Monomachine implement sample import? I was not aware of that. Or were you expecting something else?

The branch never got to implement any TM-1 functionality and was relying at the old MIDI DIN communication while the user was supplying the way to connect thorough USB.

Keep in mind that I might not remember all the details right now because this has been almost forgotten.

**Comment by dagargo** [comment]
The connector performs a custom handshake against the Monomachine that would very likely require rewriting the `machinedrum_handshake` function.

Just replace it with this and let's see if it works.

```
static gint
machinedrum_handshake (struct backend *backend)
{
  struct sds_data *sds_data;

  sds_data = g_malloc (sizeof (struct sds_data));
  sds_data->rest_time = MACHINEDRUM_REST_TIME_DEFAULT;
  sds_data->name_extension = TRUE;

  gslist_fill (&backend->fs_ops, &FS_MACHINEDRUM_SAMPLE_OPERATIONS, NULL);
  backend->data = sds_data;
  backend->destroy_data = backend_destroy_data;
  snprintf (backend->name, LABEL_MAX, "Elektron Machinedrum");

  return 0;
}
```

**Comment by ianhundere** [comment]
>Does the Monomachine implement sample import?

yeah, waveforms. 

>Just replace it with this and let's see if it works.

will do, thanks!

**Comment by ianhundere** [comment]
sorry, took me a bit to test / get this working. PR is up here: https://github.com/dagargo/elektroid/pull/238

cc @dagargo

**Comment by dagargo** [comment]
I've just merged the code from @ianhundere into master. Thanks a lot!

It adds support for Monomachine waveforms.

**Comment by dagargo** [comment]
A few notes regarding the Machinedrum support.

* I've renamed the issue to better reflect what we're doing here. SDS is already implemented and TM-1 is something that has been discussed but, for now, better leave it out of the equation.
* I've renamed the branch of this issue to `feat-add-machinedrum` too to better reflect the issue.
* If anyone is still interested in adding support for the Machinedrum, let me know if this branch is working for you.
